name: Push the Docker image to AWS ECR Repo

on:
  workflow_dispatch:
    inputs:
      directory:
         discription: 'The directory for which the image as to be built'
         required: true
         type: choice
         options:
           -backend
           -frontend
           -user-portal-frontend

  push:
    branches:
      - dev

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      #  to get sha
      - name: Get commit hash
        id: get-commit-hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build, tag, and push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: ${{ env.commit-hash }}
        run: |
          # # Find all folders with a Dockerfile
          # for dir in $(find . -name 'Dockerfile' -exec dirname {} \;); do
          #   # Extract the folder name to use as part of the image tag
          #   folder_name=$(basename "$dir")
          folder_name=${{github.event.inputs.directory}}

          # Build and tag the Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${folder_name}-$IMAGE_TAG -f ${folder_name}/Dockerfile .

          # Push the Docker image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${folder_name}-$IMAGE_TAG
          
